### PR TITLE
passing along state and "extraArguments"

### PR DESCRIPTION
**Pull request by sbussetti**

### CODE REVIEW

**Comment by machadogj** [comment]
thanks! @sbussetti

**Comment by machadogj** [comment]
hi @sbussetti how would you use the "extra" param? Can you please provide an example?

**Comment by sbussetti** [comment]
@machadogj https://github.com/gaearon/redux-thunk#injecting-a-custom-argument

**Comment by machadogj** [comment]
@sbussetti I did not know that extra param! I just published a new version of the library (1.1.0), but notice that I added an extra action so now there are 4 actions:
MY_FETCH_STARTED, MY_FETCH_SUCCEEDED, MY_FETCH_FAILED, MY_FETCH_ENDED.
This will break backward compatibility!

**Comment by sbussetti** [comment]
@machadogj makes sense to me, thanks for the heads up and for the quick merge.  Working well for me in dev today.

**Comment by machadogj** [comment]
@sbussetti can you post an example of calling `createActionThunk` and accessing the `getState` and `extra` params?

**Comment by sbussetti** [comment]
@machadogj Yeah absolutely, will get back to you on that soon.

**Comment by sbussetti** [comment]
Sorry for lateness @machadogj -- here's a use case example:

```
const store = createStore(
  reducer,
  applyMiddleware(thunk.withExtraArgument(api))
)

// later
let fetch = createActionThunk('FETCH_USER', (id, {getState, extra} => {
    let {apiSettings} = getState(),
         {api} = extra;

    return api.fetchUser(id, apiSettings);
});

```

**Pull request merged**
